# Generated by Django 2.2.1 on 2019-05-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=50)),
                ('pass2', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='sitios',
            old_name='password',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='sitios',
            old_name='user',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='sitios',
            name='calificacion',
            field=models.IntegerField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitios',
            name='precio',
            field=models.IntegerField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitios',
            name='serviciosP',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
